# Generated by Django 2.1 on 2018-08-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='text',
        ),
        migrations.RemoveField(
            model_name='template',
            name='date',
        ),
    ]
